services:
  dolt:
    build:
      context: .
      dockerfile: docker/dolt/Dockerfile
    volumes:
      - ./docker/dolt/config.yaml:/etc/dolt/servercfg.d/config.yaml
      - ./docker/dolt/data:/var/lib/dolt/
    tty: true
    stop_grace_period: 0s
  script:
    build:
      context: .
      dockerfile: docker/script/Dockerfile
    volumes:
      - .:/workspace
    tty: true
    stop_grace_period: 0s
